### ISSUE TITLE
[FIX] LogicSelector stuck in RecallLogic

### ISSUE THREAD

**Issue by hesa2020** [devakumetsu/Elobuddy#1]
Hello your Logic selector get stuck in RecallLogic.

The issue is very sample actually it happend when using champion with no mana such as garen, riven...

To fix it just go in Recall.cs
Go in the Game_OnTick function

Replace:
if (ObjectManager.Player.Distance(spawn) < 400 && ObjectManager.Player.HealthPercent() > 85 && (ObjectManager.Player.ManaPercent > 80 || ObjectManager.Player.PARRegenRate <= .0001))

For: if (ObjectManager.Player.Distance(spawn) < 400 && ObjectManager.Player.HealthPercent() > 85)

**Comment by kamekun** [comment]
Thanks fixed on the repository.

**Comment by devakumetsu** [comment]
Fixed on the repo, thanks for share this.
