### ISSUE TITLE
[BETTER FIX] LogicSelector stuck in RecallLogic

### ISSUE THREAD

**Issue by hesa2020** [devakumetsu/Elobuddy#2]
if (ObjectManager.Player.Distance(spawn) < 400 && ObjectManager.Player.HealthPercent() > 85 && (ObjectManager.Player.Mana == 0 || ObjectManager.Player.ManaPercent > 80 || ObjectManager.Player.PARRegenRate <= .0001))

This one should be a better fix if health is above 85% and user has mana to 0 ( Most likely a champ which does not use mana ) will leave the base

Else if its a champ which use mana its impossible that he has 0 mana in the base, so he will wait until it regened 80%

I am now sure what is PARRegenRate but its at the end of the OR condition so if the others are true it will leave anyway ^^
It was there before!

**Comment by devakumetsu** [comment]
Added to the repo,  thanks hesa.

(ObjectManager.Player.Mana == 0 || ObjectManager.Player.ManaPercent > 80 || ObjectManager.Player.PARRegenRate <= .0001)

Yeah need to be true on one of the condition.
